# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kishigam <kishigam@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/11 11:49:07 by kishigam          #+#    #+#              #
#    Updated: 2022/06/11 11:52:48 by kishigam         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=libftprintf.a

LIBFT_DIR	= ./libft
LIBFT		= $(LIBFT_DIR)/libft.a

INCS_DIR	= ./includes

CC			= gcc
CFLAGS		= -Wall -Wextra -Werror

.PHONY:		all clean fclean re bonus
